!!python/object:NodeDescriptor.NodeDescriptor
controls: !!python/tuple [25, 2L12B]
dimm_ram: !!python/tuple [20, 256MB]
game: !!python/object:GameDescriptor.GameDescriptor
  _control: !!python/tuple [9, Vertical]
  _dimm_ram: !!python/tuple [20, 256MB]
  _max_players: !!python/tuple [11, '2']
  _monitor: !!python/tuple [15, Vertical]
  _system: !!python/tuple [1, NAOMI]
  attributes:
  - !!python/tuple [9, Control, Vertical]
  - !!python/tuple [11, Players, '2']
  - !!python/tuple [15, Monitor, Vertical]
  - !!python/tuple [18, DIMM Reset, Testing]
  - !!python/tuple [20, DIMM RAM, 256MB]
  file_checksum: 13f006b79e89bd3722cd783c12adb837
  file_size: 33554432
  filename: Ikaruga_v3.bin
  filepath: games/Ikaruga_v3.bin
  game_id: 40
  rom_title: -IKARUGA-
  system_name: NAOMI
  title: Ikaruga
hostname: 192.168.0.2
ip: 192.168.0.2
monitor: !!python/tuple [14, Horizontal]
nickname: default
port: 10703
system: !!python/tuple [1, NAOMI]
