!!python/object:NodeDescriptor.NodeDescriptor
controls: !!python/tuple
- 25
- 2L12B
dimm_ram: !!python/tuple
- 20
- 256MB
game: !!python/object:GameDescriptor.GameDescriptor
  _control: !!python/tuple
  - 9
  - Vertical
  _dimm_ram: !!python/tuple
  - 20
  - 256MB
  _max_players: !!python/tuple
  - 10
  - '1'
  _monitor: !!python/tuple
  - 15
  - Vertical
  _system: !!python/tuple
  - 1
  - NAOMI
  attributes:
  - !!python/tuple
    - 9
    - Control
    - Vertical
  - !!python/tuple
    - 10
    - Players
    - '1'
  - !!python/tuple
    - 15
    - Monitor
    - Vertical
  - !!python/tuple
    - 18
    - DIMM Reset
    - Testing
  - !!python/tuple
    - 20
    - DIMM RAM
    - 256MB
  file_checksum: 09338511b5f281aac639c77e4ce3d841
  file_size: 125009920
  filename: TriggerHeartExelica_v6.bin
  filepath: games/TriggerHeartExelica_v6.bin
  game_id: 106
  rom_title: TRIGGERHEART EXELICA
  system_name: NAOMI
  title: Triggerheart Exelica
hostname: default.local
ip: 192.168.0.2
monitor: !!python/tuple
- 15
- Vertical
nickname: default
node_id: e7b7d426547ff42c3d46c7d5f566cde0
port: 10703
system: !!python/tuple
- 1
- NAOMI
