!!python/object:NodeDescriptor.NodeDescriptor
controls: !!python/tuple
- 25
- 2L12B
dimm_ram: !!python/tuple
- 20
- 256MB
game: !!python/object:GameDescriptor.GameDescriptor
  _control: !!python/tuple
  - 7
  - Normal
  _dimm_ram: !!python/tuple
  - 20
  - 256MB
  _max_players: !!python/tuple
  - 11
  - '2'
  _monitor: !!python/tuple
  - 14
  - Horizontal
  _system: !!python/tuple
  - 1
  - NAOMI
  attributes:
  - !!python/tuple
    - 7
    - Control
    - Normal
  - !!python/tuple
    - 11
    - Players
    - '2'
  - !!python/tuple
    - 14
    - Monitor
    - Horizontal
  - !!python/tuple
    - 16
    - DIMM Reset
    - 'Yes'
  - !!python/tuple
    - 20
    - DIMM RAM
    - 256MB
  file_checksum: 83aa92c94a26c7c6ea3bfbded1d86605
  file_size: 125829120
  filename: epr-23062a_hack.bin
  filepath: games/epr-23062a_hack.bin
  game_id: 53
  rom_title: MARVEL VS CAPCOM2  JAPAN
  system_name: NAOMI
  title: Marvel vs. Capcom 2
hostname: default.local
ip: 192.168.0.2
monitor: !!python/tuple
- 14
- Horizontal
nickname: default
node_id: e7b7d426547ff42c3d46c7d5f566cde0
port: 10703
node_type: 0
system: !!python/tuple
- 2
- NAOMI2
